### ISSUE TITLE
What one need to do to use local repository in monodevelop?

### ISSUE THREAD

**Issue by ArsenShnurkov** [mrward/nuget#2]
Right now I can add packages from remote repository. For gentoo this is not very good (because these files are binaries with unknown trust level).

My idea is to build packages locally with ebuilds, and put packages somewhere locally.

There is the "repositorypath" parameter (from here https://docs.nuget.org/consume/nuget-config-settings ) which allows to define package location for NuGet.exe. 
My idea is following:
1) create a symlink from NuGet.exe.config to /etc/nuget/nuget.conf file
2) set the location of package repository to subfolder of distfiles ("${DISTDIR}/NuGet")
3) create a symlink (or bash script with mono) /usr/bin/nuget for NuGet.exe

I need to know, 
1) how exaclty monodevelop calls the NuGet (through command line, or loads it as an assembly, and uses API directly)
2) what should be pached to make both local and external scenarios possible (might be some parts of monodevelop UI ? Just a list of repositories?)

**Comment by ArsenShnurkov** [comment]
also, do you use gitter.im?

**Comment by mrward** [comment]
If you create a local directory on your machine you can use that as the location for packages that you want to use in your projects. Then you can copy the packages you want to allow to that directory. In MonoDevelop you can then add this directory as a package source via Preferences - NuGet - Package Sources by specifying the full path to the directory (e.g. /Users/matt/packages). Then you can disable all the other package sources in Preferences and only enable the local directory. The local directory package source is displayed in the Add Packages dialog in a drop down list.

1) For older versions NuGet.exe was only used to restore packages. Newer versions do not use NuGet.exe. However all versions use a custom build of NuGet.Core.dll which is included next to the NuGet addin within MonoDevelop.
2) Nothing needs to be patched. Add the local directory to the list of package sources.

Mono 3.6 and above include NuGet and also should create a symlink so you can just use `nuget` from the command line.

The repositorypath in the NuGet.Config file is used as the destination for NuGet packages that are installed into a project. It is not a NuGet package source.

There is a [MonoDevelop gitter.im](https://gitter.im/mono/monodevelop)

**Comment by ArsenShnurkov** [comment]
i created an ebuild, which instals the nuget from this repository into GAC, and monodevelop-5.7.0-r1.ebuild, which uses that assembly (the one with NuGet addin is not used/installed).

i need to add system-wide directory during the install (of monodevelop), not from menu through UI

i don't want to disable other sources unconditionally, because user will ask, why they are disabled.

There are many projects, which include nuget packages (like GitExtensions application, for example, but there are alot of them). I want to create a common approach to deploy such projects with ebuilds. I want to compile packages first, install them to local nuget repository, then install the project. Monodevelop should use local packages, and all this should work from install cd (without the need of manual reconfiguration)

about "repositorypath" - as i understood it's local mirror of remote repositories, isn't it? What will be wrong if I will set it to system-global folder instead of currently installing project?
And if it will be the same directory, where locally compiled packages reside, the download will not occur?

**Comment by mrward** [comment]
Whilst NuGet in Visual Studio supports a system wide directory for the NuGet.Config unfortunately MonoDevelop currently does not support this. In Visual Studio the user can disable this system wide packages directory if they want to. Right now there are two options:
1. Update the NuGet.Config in the user's profile.
2. Creating a NuGet.Config in the root of the drive. MonoDevelop will check each directory starting with the solution's directory back to the root of the drive for a NuGet.Config file.

Also the NuGet.Config file configuration can be overridden by a NuGet.Config file in the solution.

I will have a look at supporting system wide NuGet.Config file in MonoDevelop. There have been some discussions with @directhex about this feature.

The repositoryPath setting was originally designed as a way to share a packages directory between multiple solutions. So instead of a NuGet package being installed into the solution's packages directory it would be installed into the repositoryPath. You can use this directory as a package source since NuGet will search that directory and one subdirectory down for .nupkg files. When I think of a local package source I always think of it as a directory with just .nupkg files in it. The difference between using repositoryPath is that the NuGet packages will be unzipped into the repositoryPath directory when you add the NuGet package to a project. Also any new NuGet package you install into a project would also be added to the repositoryPath. For a local package source that is just a directory on disk, not the repositoryPath, you could restrict it to have the set of NuGet packages you trust.

**Comment by ArsenShnurkov** [comment]
1)

> you can then add this directory as a package source via
> Preferences - NuGet - Package Sources by specifying the full path to the directory (e.g. /Users/matt/packages).

actually i can't:
![nuget-settings-in-monodevelop](https://cloud.githubusercontent.com/assets/188456/7770291/90283a18-0095-11e5-82e8-87e97d451b03.gif)

2) NuGet.Config is loaded from many different places (user directories)
/root/.config/NuGet/NuGet.Config
/home/user/.config/NuGet/NuGet.Config
i think this is here - 
https://github.com/mrward/nuget/blob/2.8.5-monodevelop/src/Core/Configuration/Settings.cs#L151

3) /usr/share/NuGet/NuGetDefaults.config 
Is this file used?
https://github.com/mrward/nuget/blob/2.8.5-monodevelop/src/Core/Configuration/ConfigurationDefaults.cs#L21

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet official package source" value="https://nuget.org/api/v2/" />
  </packageSources>
</configuration>
```

**Comment by directhex** [comment]
Please bring this discussion to the mono-packagers mailing list, it's relevant to all distributions.

https://wiki.debian.org/Teams/DebianMonoGroup/NuGet is the as-yet unimplemented plan for Debian

**Comment by mrward** [comment]
1) Not sure what Linux distribution you are using. The package sources in preferences is a gtk widget and I have not seen it not display on any Linux distribution I have used. Do any of the preferences windows show anything? Anything in the IDE logs?

2) These are used as configuration for a solution. This is mainly used to specify the repositoryPath so multiple solutions can specify a common packages directory. I believe it will also affect the package sources shown in the Add Packages dialog. It does for Visual Studio and I believe this works with MonoDevelop and Xamarin Studio.

3) NuGetDefaults.config is not used but the ~/.config/NuGet/NuGet.Config is used. These are the per user settings. When you modify the package sources in MonoDevelop, if it was working for you, then they would be saved in this config file.

**Comment by ArsenShnurkov** [comment]
3) You mean - "used" for saving from monodevelop?

Because I created that file -  /usr/share/NuGet/NuGetDefaults.config 
and nuget shows me a line from it:

```
# LANG=C nuget sources list
Registered Sources:
  1.  My Gentoo Nuget Repository [Enabled]
      https://github.com/ArsenShnurkov/NugetPackages
```

But looks like this (strangely) override sources from ~/.config/NuGet/NuGet.Config

4) also i specified "repositorypath" (in ~/.config/NuGet/NuGet.Config) as given here
https://docs.nuget.org/consume/nuget-config-file

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositorypath" value="/var/calculate/remote/distfiles/NuGet" />
  </config>
  ...
```

issued

```
 # nuget config repositorypath
 /var/calculate/remote/distfiles/NuGet
```

and 

```
# nuget install nuget
Installing 'Nuget 0.0.1'.
Successfully installed 'Nuget 0.0.1'.
# ls /var/calculate/remote/distfiles/NuGet
Nuget.0.0.1
```

So, I think it is possible just add one more config location with gentoo-specific patch, something like this:

```
            string etcPath = "/etc";
            if (Directory.Exists(etcPath))
            {
                var etcSettingsFilePath = Path.Combine(etcPath, "NuGet", Constants.SettingsFileName);
                var etcSettings = ReadSettings(
                    fileSystem ?? new PhysicalFileSystem(Directory.GetCurrentDirectory()), 
                    etcSettingsFilePath);
                if (etcSettings != null)
                {
                    validSettingFiles.Add(etcSettings);
                }
            }
```

before the line
https://github.com/mrward/nuget/blob/2.8.5-monodevelop/src/Core/Configuration/Settings.cs#L177

The next function is called LoadMachineWideSettings which have the same meaning,
but I don't see where it is used.

**Comment by mrward** [comment]
3) Yes, used by MonoDevelop when it saves its package sources.

Whilst NuGetDefault.Config is supported by NuGet I have not seen it used in practice. Although this seems to be read from a machine specific location.

4) Not sure I agree with the location of that code change. The method is loading user specific NuGet package source configuration so I would not expect it to be reading a machine specific configuration.

Instead I think we should either use the location as specified by Environment.SpecialFolder.CommonApplicationData since this is already used by NuGet when looking for machine specific settings. Or if this location is not correct on Linux and or Mac we choose a better directory and use that. This would then require a change to MonoDevelop so it supports machine specific package sources. Also it would the CommandLineMachineWideSettings class to change.

LoadMachineWideSettings is used by CommandLineMachineWideSettings but not currently used by MonoDevelop. It is used by Visual Studio.

**Comment by directhex** [comment]
CommonApplicationData is /usr/share on Linux, which is the wrong place for per-system configuration data (which belongs in /etc). We have no SpecialFolder for /etc.

/etc is part of the Filesystem Hierarchy Standard, so I don't see the harm in hardcoding it - I don't know what the correct behaviour is on Mac

**Comment by ArsenShnurkov** [comment]
I think it is possible to patch mono's implementation of

```
Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData)
```

to allow redefining builtin locations in machine.config, or in app.config.

Or create a special config like
/usr/local/etc/mono/4.5/GetFolderPath-per-application-mappings.config

But I am unsure - will upstream accept such extensions or not...

**Comment by ArsenShnurkov** [comment]
https://github.com/mrward/nuget/compare/2.8.1-monodevelop...ArsenShnurkov:2.8.1-monodevelop?expand=1

nuget-2.8.1-r1.ebuild:
https://github.com/ArsenShnurkov/shnurise/tree/master/dev-dotnet/nuget

```
nuget config repositorypath
nuget sources list
```

works for me
